name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          echo "[${{ secrets.SSH_HOST }}]:${{ secrets.SSH_PORT }} ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArKO... (replace with actual key)" >> ~/.ssh/known_hosts
          echo "[213.130.145.99]:65002 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDdnHBvmUtwkaboUl89LMtx4vzpqy6zS8hHZFYEZBMATn1bcVoXIuDNAGJmyW6dl5FopYmFdAbSbbvAkJ3yNQuo=" >> ~/.ssh/known_hosts
          echo "[213.130.145.99]:65002 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQ/RcVgP+pNa7LwCBXIWCRepaTJqW6PQ89A3z1KoCAZcIkBxCLqKBILFziIYl/0ElDNqsHIiTYh8olIQAsmUZe72pBL8iiz1x478StGIj/JYflYQ3R4Ua5Z6utaNkc6bR+ZnE3x07+tMJwiMcqSSTpgibky87OrkiHlBiwcvMgmMejxipHDomm9mw926rQgCfYf+l3X6VwX2mikf1d3zowJ9LJR3pO88PPAtqc2nA5+X0xChuUeGvPmOSHrNAgHvGn8lq1eWYEBVYi62ZzbfM3qaPy05+iSTtNQIFUf3Y5YsTlr6pBjYQaNUkNu1p5UQR939jZpCsHkAbJdt9JggeHOLLPPWJehiYvFUm5hXVMkMgAv1YkihS4ovfm3GtbLXYQosVktn8UeXCViROUvzNya6xv43RBhj61FHuOUIYmxJcYOhlTLQheh592QTVGNapnbVDDLOp+3otONg6YTvzp76YLfRZa+Bpgae7z/U21LExYjoI1XazAEDipB+fG3+k=" >> ~/.ssh/known_hosts
          echo "[213.130.145.99]:65002 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILqWRRRlOpl5XsGDrWPcPFdn+VG3oBJNX+66Fjg2EVJ6" >> ~/.ssh/known_hosts
          # Ajoutez toutes les autres clés obtenues via ssh-keyscan ici
  
      - name: Test SSH connection
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "echo 'SSH connection successful'"

      - name: Sync files to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          rsync -avz --delete --exclude '.git' -e "ssh -i ~/.ssh/id_rsa -p $SSH_PORT -o StrictHostKeyChecking=no" ./ $SSH_USERNAME@$SSH_HOST:/home/u923706777/public_html